# Generated by Django 2.1.5 on 2019-01-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='test',
            new_name='text',
        ),
    ]
